### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'parent'

### ISSUE THREAD

**Issue by onox** [NikolaiVChr/Blender-AC3D#2]
When trying to import `Models/P-51D-25NA.ac`, following exception is raised:

```
Importing P-51D-25NA.ac
+-P-51D-25NA.ac ()
  +-AN-104A (AN-104A)
  +-GearDoorHydralicArmLeft (GearDoorHydralicArmLeft)
  +-GearDoorHydralicArmRight (GearDoorHydralicArmRight)
  +-GearDoorHydralicBodyLeft (GearDoorHydralicBodyLeft)
  +-GearDoorHydralicBodyRight (GearDoorHydralicBodyRight)
  +-HydraulicLine2Left (HydraulicLine2Left)
  +-HydraulicLine2Right (HydraulicLine2Right)
  +-RearWarningRadarAntenna (RearWarningRadarAntenna)
  +-aileronTrimTabLinkageLeft (aileronTrimTabLinkageLeft)
  +-aileronTrimTabLinkageRight (aileronTrimTabLinkageRight)
  +-amorGlassLowerFrame (amorGlassLowerFrame)
  +-baffleAsssyFusSta176and27slash32 (baffleAsssyFusSta176and27slash32)
  +-canopyreleaseCableCover (canopyreleaseCableCover)
  +-coolingDoorActuatorRod (coolingDoorActuatorRod)
  +-coolingDuctRod (coolingDuctRod)
  +-cowl (cowl)
  | +-fuselage (fuselage)
  | +-dogHouse (dogHouse)
  | +-tailWheelDoorLeft (tailWheelDoorLeft)
  | +-tailFaringRight (tailFaringRight)
  | +-tailFaringLeft (tailFaringLeft)
  | +-exhaustCoverRight (exhaustCoverRight)
  | +-rudderTrimTab (rudderTrimTab)
  | +-coolingDoor (coolingDoor)
  | +-oilCoolerDoor (oilCoolerDoor)
  | +-wingFilletLeft (wingFilletLeft)
  | +-wingFilletRight (wingFilletRight)
Traceback (most recent call last):
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/__init__.py", line 171, in execute
    import_ac3d.ImportAC3D(self, context, **keywords)
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/import_ac3d.py", line 697, in __init__
    self.create_blender_data()
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/import_ac3d.py", line 795, in create_blender_data
    obj.create_blender_object(self.matlist, "", bUseLink)
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/import_ac3d.py", line 489, in create_blender_object
    obj.create_blender_object(ac_matlist, str_pre_new, bUseLink)
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/import_ac3d.py", line 489, in create_blender_object
    obj.create_blender_object(ac_matlist, str_pre_new, bUseLink)
  File "/home/onox/.config/blender/2.77/scripts/addons/io_scene_ac3d/import_ac3d.py", line 374, in create_blender_object
    self.bl_obj.parent = self.ac_parent.bl_obj
AttributeError: 'NoneType' object has no attribute 'parent'
```

**Comment by NikolaiVChr** [comment]
The ac file is malformed:

At line 108173 of the ac file:

kids 0
kids 0

This is not legal. Remove 1 of those lines.

Not sure I should make the importer be able to handle this since its not valid AC3D.
