### ISSUE TITLE
Blender 4.X compatibility

### ISSUE THREAD

**Issue by SP-NTX** [NikolaiVChr/Blender-AC3D#33]
This addon is currently not compatible with new Blender 4.0+, most likely because of new Principled BSDF shader.
When importing, the blender gives an error:
```Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\__init__.py", line 184, in execute
    import_ac3d.AC3D_OT_Import(self, context, **keywords)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 982, in __init__
    self.create_blender_data()
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 1183, in create_blender_data
    tlo = obj.create_blender_object(self.matlist, "", bUseLink, self)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 739, in create_blender_object
    child = obj.create_blender_object(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 564, in create_blender_object
    bl_material = ac_material.get_blender_material(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 201, in get_blender_material
    bl_mat = self.make_blender_mat(bl_mat)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\addons\io_scene_ac3d\import_ac3d.py", line 170, in make_blender_mat
    bsdf.inputs['Emission'].default_value = self.emis4
KeyError: 'bpy_prop_collection[key]: key "Emission" not found'```

**Comment by SP-NTX** [comment]
I looked at the code and I think the only issue are lines from 170 to 175, where the key names might be incorrect, for example:
`bsdf.inputs['Specular']` which should be `bsdf.inputs['Specular IOR Level']`

**Comment by NikolaiVChr** [comment]
Thank you for bring this to my attention. I will look into it the coming week.

**Comment by NikolaiVChr** [comment]
Fixed I hope. There is now a 4.0 branch
