### ISSUE TITLE
What branch to use with Blender 3.0.1 ?

### ISSUE THREAD

**Issue by magnetic-eagle** [NikolaiVChr/Blender-AC3D#35]
My Ubuntu distro (Studio 22.04) ships Blender 3.0.1, and only that (through snap I could install a more recent version but it refuses to run on my AMD card). I've tried both the 2.80 and 3.0 branches of this addon, and both give me the same error when exporting the AC3D file:
```
Python: Traceback (most recent call last):
  File "/home/admin/.config/blender/3.0/scripts/addons/io_scene_ac3d/__init__.py", line 354, in execute
    bpy.ops.error.message(
  File "/usr/share/blender/scripts/modules/bpy/ops.py", line 130, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/admin/.config/blender/3.0/scripts/addons/io_scene_ac3d/__init__.py", line 210, in invoke
    return wm.invoke_popup(self, width=400, height=200)
TypeError: WindowManager.invoke_popup(): takes at most 2 arguments, got 3

location: /usr/share/blender/scripts/modules/bpy/ops.py:130



location: <unknown location>:-1

```

There is no AC3D file appearing in the selected directory, so I'm actually unable to export to AC3D ! :(

**Comment by magnetic-eagle** [comment]
XD I was exporting from edit mode … but the error itself can be fixed with this patch:
```
diff --git a/io_scene_ac3d/__init__.py b/io_scene_ac3d/__init__.py
index 90f3986..c04728d 100644
--- a/io_scene_ac3d/__init__.py
+++ b/io_scene_ac3d/__init__.py
@@ -207,7 +207,7 @@ class AC3D_OT_Message(Operator):
 
     def invoke(self, context, event):
         wm = context.window_manager
-        return wm.invoke_popup(self, width=400, height=200)
+        return wm.invoke_popup(self, width=400)
 
     def draw(self, context):
         self.layout.label(text="A message has arrived")
```

**Comment by NikolaiVChr** [comment]
I have made a new branch with this change plus another change, thanks
